Develop
mpyatetskyi/flask_aws pull request #10
Opened 2021-03-02 15:52 UTC by mpyatetskyi

2021-03-02 16:10 UTC, tpashkevych-exos commented on tests/conftest.py
> +    tester = app.test_client()
you have the fixture `client` above, so you don't need to create another one each time

2021-03-02 16:10 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +def test_game_id_in_b_response(data):
naming should be comprehensive

2021-03-02 16:11 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert b'game_id' in data.data
check json when you have json

2021-03-02 16:12 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +def test_user_cards_in_json_response(data_json):
one test can have multiple assertions. so it's better to collect small checks from the same response in one test

2021-03-02 16:13 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert type(data_json['user_cards'][0]) == dict
you have a deserializer - try to use it instead and check if it's loaded correctly

2021-03-02 16:15 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert type(data_json['dealer_cards']) == list
check the size

2021-03-02 16:15 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert type(data_json['dealer_cards']) == list
+ don't expose it to the user if the game does not allow it

2021-03-02 16:16 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert type(data_json['dealer_cards'][1]) == dict
don't repeat the code. use `[all](https://docs.python.org/3/library/functions.html#all)` for example

2021-03-02 16:17 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert data_json['dealer_cards'][0]['rank'] in range(1, 15)
try to see the patterns

2021-03-04 11:50 UTC, tpashkevych-exos commented on tests/conftest.py
> +@pytest.fixture(scope="module")
why module?

2021-03-04 11:52 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert type(data_json['dealer_cards']) == list
test_keys seems a bit excessive in this context - you basically check here for the keys too

2021-03-04 11:54 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert all([type(card['rank']) == int for
Seems excessive also, since you check for the range below which will not allow anything but integer

2021-03-04 11:57 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    assert all([type(card['suit']) == int for
same here

2021-03-04 12:04 UTC, tpashkevych-exos requested changes
let's reduce the amount of code

2021-03-05 09:00 UTC, mpyatetskyi commented on tests/conftest.py
> +@pytest.fixture(scope="module")
Because with scope "module" my fixters run just once per bodule/package not before every test.
Just as I wanted and this solves my problem with NoneType when there`re no cards left in the deck

2021-03-05 18:39 UTC, tpashkevych-exos commented on tests/test_route_newgame.py
> +    data = data_json['user_cards'] + data_json['dealer_cards']
does it work?

2021-03-05 18:45 UTC, tpashkevych-exos approved these changes

2021-03-10 15:38 UTC, merged